#!/syntax/bash

function Main.put {
	declare -- ROOT="$1" DISTRIB="$2" COMPONENT="$3"
	shift 3
	Util.arg1_or_usage "$@" || return 1
}

function Main.update {
	declare -- ROOT="$1"
	Util.arg1_or_usage "$@" || return 1
}

function Main.import {
	declare -- ROOT="$1"
	Util.arg1_or_usage "$@" || return 1
}

function Main.daemon {
	declare -- ROOT="$1"
	Util.arg1_or_usage "$@" || return 1
}

function Main.rotate {
	declare -- ROOT="$1"
	Util.arg1_or_usage "$@" || return 1
}
