#!/syntax/bash

function architectures {
	ARCHS=( "$@" )
}

function codename {
	CODENAME="$@"
}

function origin {
	ORIGIN="$@"
}

function label {
	LABEL="$@"
}

function description {
	DESC="$@"
}
