#!/syntax/bash

function Util.temp {
	tempfile --prefix "$1-" --suffix '.debrepo'
}

function Util.hash {
	"${1}sum" "$2" | cut -d ' ' -f 1
}

function Util.bad_bash? {
	(
		declare -n zomg &> /dev/null && exit 1
	)
}

function Util.usage! {
	cat <<-EOH
		Usage: $ME put    ROOT DISTRIB COMPONENT FILENAME...
		       $ME mkrepo ROOT DISTRIB...
		       $ME update ROOT
		       $ME rotate ROOT
		       $ME daemon ROOT
	EOH
}

function Util.arg1_or_usage {
	[[ "$1" ]] && return 0
	Util.usage!
	return 1
}

function Util.error {
	echo "FAIL $@"
	echo "FAIL $@" >& 2
}

function Util.send {
	declare -- ROOT="$1"
	shift
	coproc nc -n -q -1 -U "$ROOT/socket"
	echo "$@" >& "${COPROC[1]}"
	read <& "${COPROC[0]}"
	kill -HUP "$COPROC_PID"
	wait &> /dev/null
	echo "$REPLY"
}
